#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

# Fetch the GIT diff and format it as command input:
DIFF=$(git diff --staged --name-only | cat)

# Grumphp env vars
export GRUMPHP_GIT_WORKING_DIR="$(git rev-parse --show-toplevel)"

# Run GrumPHP
docker compose exec -T -e DIFF="$DIFF" php bash -c 'printf "$DIFF" | ./vendor/bin/grumphp git:pre-commit --skip-success-output'
